apiVersion: apps/v1
kind: Deployment
metadata:
  name: minhaagendadecontatos-api  # Alterado para não ter pontos
  labels:
    app: minhaagendadecontatos-api  # Alterado para manter consistência
spec:
  replicas: 3
  selector:
    matchLabels:
      app: minhaagendadecontatos-api  # Alterado para manter consistência
  template:
    metadata:
      labels:
        app: minhaagendadecontatos-api  # Alterado para manter consistência
    spec:
      containers:
      - name: minhaagendadecontatos-api  # Alterado para não ter pontos
        image: minhaagendadecontatos.api
        ports:
        - containerPort: 10443
        - containerPort: 10080
        env:
        - name: SERVER_HOST
          valueFrom:
            configMapKeyRef:
              name: minhaagendadecontatos.api.dados
              key: SERVER_HOST
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: senhas
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: senhas
              key: DB_PASSWORD
        - name: ASPNETCORE_URLS
          value: "https://+:443;http://+:80"
        volumeMounts:
        - name: usersecrets
          mountPath: /root/.microsoft/usersecrets
          readOnly: true
        - name: aspnethttps  # Este volume deve ser definido
          mountPath: /root/.aspnet/https
          readOnly: true
      volumes:
      - name: usersecrets
        secret:
          secretName: senhas
          items:
          - key: DB_PASSWORD
            path: DB_PASSWORD  # Mantenha a definição do item
      - name: aspnethttps  # Definição do volume
        secret:  # Supondo que este volume é um secret
          secretName: aspnethttps-secret  # Altere para o nome correto do seu secret
