version: '3.8'

services:
  # DATABASE
  minhaagenda-database:
    container_name: minhaagenda-database
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: minhaagenda
    networks:
      - mynw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  # PGADMIN4
  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin_4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: etapa2@fiap.com.br
      PGADMIN_DEFAULT_PASSWORD: etapa2
    ports:
      - 15432:80
    networks:
      - mynw

  # API
  minhaagenda:
    container_name: minhaagenda
    image: ${DOCKER_REGISTRY-}minhaagenda
    ports:
      - 8888:80
    build:
      context: .
      dockerfile: ./src/Backend/MinhaAgendaDeContatos.Api/Dockerfile
    depends_on:
      minhaagenda-database:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DB_HOST: minhaagenda-database
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: minhaagenda
    networks:
      - mynw

  # PROMETHEUS
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      minhaagenda:
        condition: service_started
    networks:
      - mynw

  # GRAFANA
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - mynw

volumes:
  postgres_data:

networks:
  mynw:
    driver: bridge
