version: '3.4'

services:
  minhaagendadecontatos.api:
    image: ${DOCKER_REGISTRY-}minhaagendadecontatosapi
    build:
      context: .
      dockerfile: src/Backend/MinhaAgendaDeContatos.Api/Dockerfile
