version: '3.8'

services:

  # DATABASE
  minhaagenda-database:
    container_name: minhaagenda-database
    image: postgres:latest
    ports:
      - 5432:5432
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: minhaagenda
    networks:
      - mynw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
 
  # API
  minhaagendadecontatos.api:
    container_name: minhaagenda
    image: minhaagenda-api:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "10080:80"
      - "10443:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      minhaagenda-database:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - mynw

  # PROMETHEUS
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - mynw

  # RABBITMQ
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - 5673:5672
      - 15692:15692
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_PROMETHEUS_EXPORTER: true
    networks:
      - mynw
    healthcheck:
      test: ["CMD-SHELL", "rabbitmqctl status"]
      interval: 30s
      timeout: 30s
      retries: 10

  # GRAFANA
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - mynw

  # PGADMIN4  
  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin_4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@gmail.com
      PGADMIN_DEFAULT_PASSWORD: dev     
    ports: 
      - 15432:80
    networks: 
      - mynw

volumes:
  postgres_data:

networks:
  mynw:
    driver: bridge
    attachable: true
