apiVersion: v1
kind: Secret
metadata:
  name: minhaagenda-db-secret
type: Opaque
data:
  connectionString: "SG9zdD1taW5oYWFnZW5kYS1kYXRhYmFzZTtQb3J0PTU0MzI7RGF0YWJhc2U9bWluaGFhZ2VuZGE7VXNlcm5hbWU9cG9zdGdyZXM7UGFzc3dvcmQ9cG9zdGdyZXM7VGltZW91dD02MDs="
