apiVersion: apps/v1
kind: Deployment
metadata:
  name: minhaagenda-api-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: minhaagenda-api
  template:
    metadata:
      labels:
        app: minhaagenda-api
    spec:
      containers:
      - name: minhaagenda-api
        image: denisjesus/minhaagenda-api:dev  # Usando imagem diretamente
        resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
        ports:
        - containerPort: 5001
        env:
        - name: DATABASE_CONNECTION_STRING
          value: "Host=minhaagenda-db-service;Port=5432;Database=minhaagenda;Username=postgres;Password=postgres;Timeout=60;"  # Ajuste para o nome correto do serviço do DB
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
