apiVersion: v1
kind: Pod
metadata:
  name: minhaagenda-pod
  labels:
    app: minhaagenda
spec:
  containers:
  - name: minhaagenda
    image: minhaagenda-api:dev # Troque pela imagem correta
    ports:
      - containerPort: 80
    env:
      - name: ASPNETCORE_ENVIRONMENT
        value: "Development"
      - name: DB_HOST
        value: "minhaagenda-database"
      - name: DB_PORT
        value: "5432"
      - name: DB_USER
        value: "postgres"
      - name: DB_PASSWORD
        value: "postgres"
      - name: DB_NAME
        value: "minhaagenda"
      - name: RABBITMQ_HOST
        value: "rabbitmq"
      - name: RABBITMQ_PORT
        value: "5672"
  - name: minhaagenda-database
    image: postgres:latest
    env:
      - name: POSTGRES_USER
        value: "postgres"
      - name: POSTGRES_PASSWORD
        value: "postgres"
      - name: POSTGRES_DB
        value: "minhaagenda"
    ports:
      - containerPort: 5432
    volumeMounts:
      - name: postgres-data
        mountPath: /var/lib/postgresql/data
  volumes:
    - name: postgres-data
      emptyDir: {}
