apiVersion: v1
kind: Secret
metadata:
  name: senhas
type: Opaque
stringData:
  DB_USER: postgres
  DB_PASSWORD: postgres
  rabbitmq: guest
  grafana: admin
  prometheus: prometheus
  pgadmin4: pgadmin4
  

