apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-postgres
spec:
  accessModes:
    - ReadWriteOnce  
  resources:
    requests:
      storage: 15Gi
  storageClassName: csi-hostpath-sc