//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinhaAgendaDeContatos.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMensagensDeErro {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMensagensDeErro() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MinhaAgendaDeContatos.Exceptions.ResourceMensagensDeErro", typeof(ResourceMensagensDeErro).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum contato encontrado com esse email..
        /// </summary>
        public static string CONTATO_EMAIL_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("CONTATO_EMAIL_NAO_ENCONTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum contato encontrado..
        /// </summary>
        public static string CONTATO_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("CONTATO_NAO_ENCONTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum contato encontrado com esse prefixo..
        /// </summary>
        public static string CONTATO_PREFIXO_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("CONTATO_PREFIXO_NAO_ENCONTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail do contato deve ser informado..
        /// </summary>
        public static string EMAIL_CONTATO_EMBRANCO {
            get {
                return ResourceManager.GetString("EMAIL_CONTATO_EMBRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail do contato é inválido..
        /// </summary>
        public static string EMAIL_CONTATO_INVALIDO {
            get {
                return ResourceManager.GetString("EMAIL_CONTATO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail informado já está registrado na base de dados..
        /// </summary>
        public static string EMAIL_JA_REGISTRADO {
            get {
                return ResourceManager.GetString("EMAIL_JA_REGISTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro desconhecido..
        /// </summary>
        public static string ERRO_DESCONHECIDO {
            get {
                return ResourceManager.GetString("ERRO_DESCONHECIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do contato deve ser informado..
        /// </summary>
        public static string NOME_CONTATO_EMBRANCO {
            get {
                return ResourceManager.GetString("NOME_CONTATO_EMBRANCO", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to O prefixo do contato está em branco.
        ///   
        ///   Consulta uma cadeia de caracteres localizada semelhante a Prefixo do contato inválido ou não informado.
        /// </summary>
        public static string PREFIXO_CONTATO_EMBRANCO {
            get {
                return ResourceManager.GetString("PREFIXO_CONTATO_EMBRANCO", resourceCulture);
            }
        }

        /// <summary>
        /// 
        ///   Looks up a localized string similar to O telefone do contato deve ser informado..
        ///   Consulta uma cadeia de caracteres localizada semelhante a Telefone do contato inválido ou não informado.
        /// </summary>
        public static string TELEFONE_CONTATO_EMBRANCO {
            get {
                return ResourceManager.GetString("TELEFONE_CONTATO_EMBRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O telefone do contato é inválido..
        /// </summary>
        public static string TELEFONE_CONTATO_INVALIDO {
            get {
                return ResourceManager.GetString("TELEFONE_CONTATO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum contato encontrado com esse telefone.
        /// </summary>
        public static string TELEFONE_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("TELEFONE_NAO_ENCONTRADO", resourceCulture);
            }
        }
    }
}
