apiVersion: apps/v1
kind: Deployment
metadata:
  name: minhaagendadecontatosapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: minhaagendadecontatosapi
  template:
    metadata:
      labels:
        app: minhaagendadecontatosapi
    spec:
      containers:
      - name: minhaagendadecontatosapi
        image: alexandreescossio/minhaagendadecontatosapi
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: minhaagendadecontatosapi
spec:
  selector:
    app: minhaagendadecontatosapi
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus
        ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  selector:
    app: prometheus
  ports:
  - port: 9090
    targetPort: 9090
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  selector:
    app: grafana
  ports:
  - port: 3000
    targetPort: 3000
  type: NodePort