apiVersion: apps/v1
kind: Deployment
metadata:
  name: minhaagendadecontatosapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: minhaagendadecontatosapi
  template:
    metadata:
      labels:
        app: minhaagendadecontatosapi
    spec:
      containers:
      - name: minhaagendadecontatosapi
        image: alexandreescossio/minhaagendadecontatosapi
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: minhaagendadecontatosapi
spec:
  selector:
    app: minhaagendadecontatosapi
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
  type: NodePort