# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

#Definindo quando o WorkFlow será disparado
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

#Definindo os jobs que o workFlow executará
jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        #env:
        #  POSTGRES_DB: testdb
        #  POSTGRES_USER: testuser
        #  POSTGRES_PASSWORD: testpassword
        options: >-
          --health-cmd="pg_isready -U testuser -d testdb"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

    - name: Unit Test
      #env:
      #  POSTGRES_USER: postgres
      #  POSTGRES_PASSWORD: postgres
      #  POSTGRES_HOST: localhost
      run: dotnet test --no-build --verbosity normal --filter "FullyQualifiedName!~IntegrationTest"
    
    - name: Integration Test
      #env:
      #  POSTGRES_USER: postgres
      #  POSTGRES_PASSWORD: postgres
      #  POSTGRES_HOST: localhost
      run: dotnet test --no-build --verbosity normal --filter "FullyQualifiedName~IntegrationTest"